{
  "embeddings": [
    {
      "tensorName": "Al-Fajar Insights",
      "tensorShape": [
        6236,
        50
      ],
      "tensorPath": "https://github.com/wasimazad/tensorflow_data/blob/main/ayat_vecs.tsv",
      "metadataPath": "https://github.com/wasimazad/tensorflow_data/blob/main/ayat_meta.tsv"
    }
  ]
}
